import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tactable Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Tactable assessment
        </h1>

        <p className={styles.description}>
          Get started by choosing which assesment you want to go to
        </p>

        <div className={styles.grid}>
          <a href="/posts" className={styles.card}>
            <h2>Frontend &rarr;</h2>
            <p>Posts from an API response are rendered and shown.</p>
          </a>

          <a href="/backend" className={styles.card}>
            <h2>Backend &rarr;</h2>
            <p>Backend Assessment (WIP)</p>
          </a>

          <a href="/data" className={styles.card}>
            <h2>Data &rarr;</h2>
            <p>Data Assessment (WIP)</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/fons95/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by Alfonso Diaz Infante
        </a>
      </footer>
    </div>
  )
}

export default Home
